services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - example-db:/var/lib/postgresql/data

  app:  # Changed from "example" to "app"
    build: 
      context: .
    environment:
      PROD_DB_NAME: postgres
      PROD_DB_USERNAME: postgres
      PROD_DB_PASSWORD: postgres
      PROD_DB_HOSTNAME: postgres
    depends_on:
      - postgres
    ports:
      - "3000:3000"

volumes:
  example-db:

